name: renew
on:
  schedule:
    - cron: '30 11 * * 1' # Every Monday at 11:30 AM
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Playwright and Chromium
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install chromium

      - name: Run the renewal script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python renew.py
